In [ ]:
import kaggle
import pandas as pd
import numpy as np
import os

Load Data

In [21]:
electricity_data = pd.read_csv('complete_dataset.csv')

In [22]:
electricity_data

,date,demand,RRP,demand_pos_RRP,RRP_positive,demand_neg_RRP,RRP_negative,frac_at_neg_RRP,min_temperature,max_temperature,solar_exposure,rainfall,school_day,holiday
0,2015-01-01,99635.030,25.633696,97319.240,26.415953,2315.790,-7.240000,0.020833,13.3,26.9,23.6,0.0,N,Y
1,2015-01-02,129606.010,33.138988,121082.015,38.837661,8523.995,-47.809777,0.062500,15.4,38.8,26.8,0.0,N,N
2,2015-01-03,142300.540,34.564855,142300.540,34.564855,0.000,0.000000,0.000000,20.0,38.2,26.5,0.0,N,N
3,2015-01-04,104330.715,25.005560,104330.715,25.005560,0.000,0.000000,0.000000,16.3,21.4,25.2,4.2,N,N
4,2015-01-05,118132.200,26.724176,118132.200,26.724176,0.000,0.000000,0.000000,15.0,22.0,30.7,0.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101,2020-10-02,99585.835,-6.076028,41988.240,26.980251,57597.595,-30.173823,0.625000,12.8,26.0,22.0,0.0,N,N
2102,2020-10-03,92277.025,-1.983471,44133.510,32.438156,48143.515,-33.538025,0.583333,17.4,29.4,19.8,0.0,N,N
2103,2020-10-04,94081.565,25.008614,88580.995,26.571687,5500.570,-0.163066,0.062500,13.5,29.5,8.4,0.0,N,N
2104,2020-10-05,113610.030,36.764701,106587.375,39.616015,7022.655,-6.511550,0.083333,9.1,12.7,7.3,12.8,N,N
2105,2020-10-06,122607.560,75.771059,122607.560,75.771059,0.000,0.000000,0.000000,8.9,12.6,5.8,1.0,N,N

In [23]:
electricity_data.columns

Index(['date', 'demand', 'RRP', 'demand_pos_RRP', 'RRP_positive',
       'demand_neg_RRP', 'RRP_negative', 'frac_at_neg_RRP', 'min_temperature',
       'max_temperature', 'solar_exposure', 'rainfall', 'school_day',
       'holiday'],
      dtype='object')

In [24]:
cleaned_data = electricity_data[['date', 'demand', 'min_temperature', 'max_temperature']]

In [25]:
cleaned_data.isna().sum()

date               0
demand             0
min_temperature    0
max_temperature    0
dtype: int64

In [28]:
cleaned_data[['min_temperature', 'max_temperature']]

      min_temperature  max_temperature
0                13.3             26.9
1                15.4             38.8
2                20.0             38.2
3                16.3             21.4
4                15.0             22.0
...               ...              ...
2101             12.8             26.0
2102             17.4             29.4
2103             13.5             29.5
2104              9.1             12.7
2105              8.9             12.6

[2106 rows x 2 columns]

In [36]:
cleaned_data.loc[:, 'avg_temperature'] = cleaned_data[['min_temperature', 'max_temperature']].mean(axis=1)
cleaned_data.drop(columns=['min_temperature', 'max_temperature'], inplace=True)
cleaned_data.head()

C:\Users\User\AppData\Local\Temp\ipykernel_4240\733995033.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data.drop(columns=['min_temperature', 'max_temperature'], inplace=True)

         date      demand  avg_temperature
0  2015-01-01   99635.030            20.10
1  2015-01-02  129606.010            27.10
2  2015-01-03  142300.540            29.10
3  2015-01-04  104330.715            18.85
4  2015-01-05  118132.200            18.50